spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tiny_link
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${rds.host}
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true